### ISSUE TITLE
Messages which doesn't have Message-ID cannot all be retrieved.

### ISSUE THREAD

**Issue by sanzero** [Webklex/laravel-imap#121]
Hi Webklex,

Thanks for providing great library!

I found an issue that messages sent from yahoo web mail client surprisingly didn't have Message-ID.
Is it just me or this can happen, so I think MessageCollection's key should be replaced with alternatives ($msgno?) in the absence of Message-ID .

Sample header info.
> From MY NAME Tue Jul 10 20:56:49 2018
X-YMail-OSG: Random string
Received: from [ip.add.re.ss] by *.*.*.yahoo.co.jp via HTTP; Tue, 10 Jul 2018 20:56:49 JST
X-Mailer: YahooMailWebService/0.8.111_74
X-YMail-JAS: Random string
Date: Tue, 10 Jul 2018 20:56:49 +0900 (JST)
From: sender name <sender@yah**.co.jp>
Reply-To: sender name <sender@yah**.co.jp>
Subject: here is subject
To: "receiver@***.co.jp" <receiver@***.co.jp>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="some-digits-are=:here"
Content-Length: 529

The relevant code is here.

https://github.com/Webklex/laravel-imap/blob/44aa0c3c28145aa61e6cbcd556a18ab5890395d1/src/IMAP/Folder.php#L300

Thank you.

**Comment by Webklex** [comment]
Hi @sanzero ,
thanks for your report. Well I havn't heard of this "feature" :D

Since I don't own a yahoo Mail account, would you mind sending one to github[-at-]webklex.com? This way I can take a better look at it .

I wouldn't like the idea of using the message_id - some sort of trust issue (had to many problems with changinging ids)...

Best regrads
