### ISSUE TITLE
imap_fetchbody() expects parameter 4 to be long, string given

### ISSUE THREAD

**Issue by kikemarto** [Webklex/laravel-imap#13]
Hi,

I have problem with this error:

"imap_fetchbody() expects parameter 4 to be long, string given"

I'm testing the example. Need solution but i do not understand.

Image: [http://imgur.com/uCAjqKO](http://imgur.com/uCAjqKO)

Greeating.

**Comment by Webklex** [comment]
Hi kikemarto,
please make shure you've entered a valid fetch option inside your `config/imap.php` file. For futher information take a look at the official documentation: [http://php.net/manual/en/imap.constants.php](http://php.net/manual/en/imap.constants.php).

It seem you arn't providing an integer value. So if you like check if `config('imap.options.fetch', FT_UID)` returns an integer.

Since I can't reproduce this error I decided to enhanced (added) a $fetch_option setter method in order to check if the given prameter is valid. If not it will be converted into an integer. I hope it will solve your problem :)

Ref. to new version: [1.0.2.10](https://github.com/Webklex/laravel-imap/releases/tag/1.0.2.10)
