### ISSUE TITLE
using tls encryption I am unable to connect. 

### ISSUE THREAD

**Issue by smruti-Bapi0001** [Webklex/laravel-imap#132]
Hi, 
First of all thanks for this awesome plugin. But some help needed as I am sure I am missing out something.
If I am connecting via tls encryption I am getting error and unable to make connection. But if I am connecting via ssl encryption I am able to connect but getting empty array but actually there are mails.
```php
imap.php
      'accounts' => [

            'default' => [// account identifier
            'host'  => env('IMAP_HOST', 'outlook.office365.com'),
            'port'  => env('IMAP_PORT', 993),
            'protocol'  => env('IMAP_PROTOCOL', 'imap'), //might also use imap, [pop3 or nntp (untested)]
            'encryption'    => env('IMAP_ENCRYPTION', 'TLS'), // Supported: false, 'ssl', 'tls'
            'validate_cert' => env('IMAP_VALIDATE_CERT', true),
            'username' => env('IMAP_USERNAME', 'username@abc.com'),
            'password' => env('IMAP_PASSWORD', 'password'),
],
```
controller.php
```php
use Webklex\IMAP\Facades\Client;
 public function getEmails(){
        $oClient = Client::account('default');
        $oClient->connect();        
        $oFolder = $oClient->getFolder('INBOX.name');       
        $aMessage = $oFolder->query()->all()->get();
        dd($aMessage);
    }
```
Response: 
```
MessageCollection {#617 ▼
  #items: []
}
```

**Comment by Webklex** [comment]
Hi @smruti-Bapi0001 ,
please try the following and check the output:
```php
        $aFolder = $oClient->getFolders();

        /** @var Folder $oFolder */
        foreach($aFolder as $oFolder){
            $__folder = $oClient->getFolder($oFolder->fullName);
            echo $oFolder->fullName.' @ '.$oFolder->getMessages()->count().
                     ' => '.$__folder->getMessages()->count()."\n";
        }
```

It should result in something like this:
```
Archiv @ 0 => 0
Drafts @ 0 => 0
Deleted @ 0 => 0
Sent @ 0 => 0
INBOX.aKYCUhbMTutarWZ2 @ 0 => 0
INBOX.Bv1hJyRqAKFcXpL4 @ 0 => 0
INBOX.ptm7TQVjEQZ96Ogg @ 0 => 0
INBOX.yCLAMHCqmmc0hfuh @ 0 => 0
Junk @ 2 => 2
Notes @ 0 => 0
Outbox @ 0 => 0
Inbox @ 3 => 3
```
Please share your output if it has any false numbers in it (remove any personal information before posting it).

If all given numbers match, I would guess you misspelled the folder name or perhaps used a wrong delimiter ("." instead of "/")? Anyway you should be able to get the messages since they have to be fetched in order to be counted.

Please go to https://support.office.com/en-us/article/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040?ui=en-US&rs=en-US&ad=US and make sure you've done all required steps to enable the imap access.

If you are using a shred mailbox please head over to this issue: https://github.com/Webklex/laravel-imap/issues/78 @SirPoot- has written a little tutorial on how to set it up :)

Regarding the tls feature; I can reproduce this behavior by using my outlook test account but I honestly have no clue why it happens, since it shouldn't happen in the first place.. (This occures to me only on outlook). 
I guess you received this error message?
```
Webklex\IMAP\Exceptions\ConnectionFailedException]                                                                        
  imap_open(): Couldn't open stream {outlook.office365.com:993/imap/tls}. [CLOSED] IMAP connection broken (server response)  
```

I'll take a closer look at it as soon as I have some time for it :) However please let me know if you have any further information or questions.

Best regards

P.s.:
Outlook seems to be special sometimes. Previous users have reported that changing the config option `imap.options.fetch` to `null` solved their problem sometimes..

**Comment by smruti-Bapi0001** [comment]
Hi @Webklex 

Thanks for your quick response. I am unable to figure out why I am getting invalid arguments passed for foreach error on running

 $aFolder = $oClient->getFolders();

I tried to debug and I was able to get $items as an array. 

Anyways I will get back to you once I get some result. 

About the tls error you mentioned I am getting that exact error.

**Comment by codermahadi** [comment]
imap.php 
 'default' => [// account identifier
            'host'  => env('IMAP_HOST', 'mail.opced.com'),
            'port'  => env('IMAP_PORT', 993),
            'protocol'  => env('IMAP_PROTOCOL', 'imap'), //might also use imap, [pop3 or nntp (untested)]
            'encryption'    => env('IMAP_ENCRYPTION', 'ssl'), // Supported: false, 'ssl', 'tls', 'notls', 'starttls'
            'validate_cert' => env('IMAP_VALIDATE_CERT', true),
            'username' => env('IMAP_USERNAME', 'root@mail.opced.com'),
            'password' => env('IMAP_PASSWORD', ''),
            'authentication' => env('IMAP_AUTHENTICATION', null),
            'proxy' => [
                'socket' => null,
                'request_fulluri' => false,
                'username' => null,
                'password' => null,
            ]
        ],

but show connection faild
