### ISSUE TITLE
Undefined property: stdClass::$uidnext after upgrading 1.4.1

### ISSUE THREAD

**Issue by INattivo** [Webklex/laravel-imap#210]
Hi,
After upgrade from 1.4.0 to 1.4.1 component going in exception "Undefined property: stdClass::$uidnext".
The component before upgrading worked without any issue.

I'll post the last step of trace

Trace: #0 /var/www/laravel/vendor/webklex/laravel-imap/src/IMAP/Message.php(986): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/var/www/larave...', 986, Array)
#1 /var/www/laravel/app/Console/Commands/PrecessFacileLead.php(135): Webklex\IMAP\Message->moveToFolder('lead.inviati')
#2 /var/www/laravel/app/Console/Commands/PrecessFacileLead.php(319): App\Console\Commands\PrecessFacileLead->processFiles(true, false)

- OS: CentOS Linux release 7.6.1810
- PHP: PHP 7.2.17 (fpm-fcgi) (built: Apr  3 2019 10:04:33)
- APACHE: 2.4.6 (CentOS)

Thanks

**Comment by ksgush1** [comment]
Confirmed! Had to downgrade because of this issue!

**Comment by Webklex** [comment]
Hi @INattivo @ksgush1 ,
if you dump `$folder->getStatus(IMAP::SA_ALL)` do you get any result? If so what does it show?

It should return an object containing an attribute called "uidnext".

**Comment by CarlKlein** [comment]
Hi @Webklex,

I run into the same issue with 1.4.2. If I dump $folder->getStatus(IMAP::SA_ALL) I get the following:

object(stdClass)#630 (1) {
  ["flags"]=>
  int(0)
}

So that's not what you expect. This concerns an Exchange server, could it be that this does not have a full implementation of the imap_status command?

**Comment by Webklex** [comment]
@CarlKlein ,
thanks for testing. Could it be related to this: https://bugs.php.net/bug.php?id=73186?

**Comment by CarlKlein** [comment]
Hi, that seems very likely. Not using an Office 365 server here though. Older Exchange version but what is shown is exactly what is displayed as Actual Result in the description.

**Comment by Webklex** [comment]
Please try to use` Message::move($mailbox)`. It won't return the moved Message object but it's a way to move the message anyway. I'm not sure how I could bypass the current imap_status() problem. 

I can't think of any alternative way to determine the next uid of the target mailbox. The only thing I could think of is a new query such as `$next_uid = $target_folder->query()->all()->count() + 1`. But even this could fail since the mailserver could be setup to have its uid start at 100 or 1000 etc...

**Comment by CarlKlein** [comment]
Can confirm that using Message:move($mailbox) works OK on 1.4.2. I don't think you should use something like this: `$target_folder->query()->all()->count() + 1`. The UID seems to be a sequence number that just increases.

I don't really see how to resolve this other than just checking if a next uid can be found and if not, just return null.
