### ISSUE TITLE
no messages after getFolder() vs getFolders()

### ISSUE THREAD

**Issue by iwen65** [Webklex/laravel-imap#234]
I am using Exchange 2013 with activated IMAP access. The connection is valid. I can access the mailbox with thunderbird and outlook. 

I try to access the mailbox using php with this module. If i have opened the folder directly, I do not receive any message. If I have retrieved all folders and use the folder-object inside a loop, it works. 

`
// At this point I have a VALID connection (client)

$mailbox = 'INBOX';

// Try #1:

$folder = $client->getFolder($mailbox);
$messages = $folder->messages()->limit(100)->get();
// Output: NO MESSAGES 

$folders = $client->getFolders(false);
  foreach ($folders as $folder) {
  if ($folder->path == $mailbox) {
        $messages = $folder->messages()->limit(100)->get();
         break;
   }
// Output:: 100 MESSAGES

`

**Comment by Webklex** [comment]
Hi @iwen65 ,
have you tried to use different parameters? 
```
Client::getFolder($folder_name, $attributes = 32, $delimiter = null, $prefix_address = true)
```

This function is completely experimental, caused by the fact that I have no clue what `$attributes` does. I only figured out that the number 32 seems to work in my case :) So feel free to poke arround and please let me know if you know more about this number.

Best regards
