### ISSUE TITLE
Undefined property: stdClass::$disposition

### ISSUE THREAD

**Issue by k3youmin** [Webklex/laravel-imap#253]
![image](https://user-images.githubusercontent.com/15870174/65562031-4b5d0380-df77-11e9-9fc2-4904693bc48a.png)

![image](https://user-images.githubusercontent.com/15870174/65562035-50ba4e00-df77-11e9-9a57-81614df91ac8.png)

I have an error when fetching the body of the email. How can I solved this error "Undefined property: stdClass::$disposition"

**Comment by ianpbh** [comment]
I had this issue while ago when trying to fetch the messages to, but assumed it was a character error from a specific message, cause' i tried the limit Method and the error stopped.
Try to limit your query to 10 e-mails for example, and see if the error happens again

`$oFolder->messages()->all()->limit(10)->get();`

**Comment by girvydas** [comment]
ErrorException
Notice: Undefined property: stdClass::$disposition
---
src/IMAP/Message.php line 721


Need to check $structure->ifdisposition first

**Comment by maxiz22** [comment]
Hi i have same issue :
Undefined property: stdClass::$disposition
httpdocs/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php:223

i see girvydas working with this problem , I will be following the update

**Comment by mxl** [comment]
Could you release package update? It's a critical bug.

**Comment by ricus-zero2one** [comment]
I'm still experiencing this bug using the latest version. Am I the only one?

**Comment by girvydas** [comment]
It's already merged in 1.4.4 version.

**Comment by ricus-zero2one** [comment]
@girvydas that's what I thought, and I also saw the PR that was fixing this getting merged in. I updated again this morning because I noticed a new release and to ensure I'n on the latest.

This is from the lock file on the server, we are definitely using 1.4.4

![image](https://user-images.githubusercontent.com/17425015/69939438-86843180-14e8-11ea-86b4-fcda97df5c52.png)

And then in our error logs for today:

![image](https://user-images.githubusercontent.com/17425015/69939475-9ef44c00-14e8-11ea-8ff1-f9ac8d68ac52.png)

We use horizon to process mailboxes every minute. I know horizon is a long-lived process, I've stopped and started it multiple times trying to debug this, and horizon:terminate is also part of our deployment so I don't think that's the issue.

While I'm here, I've noticed us getting errors for emails that are not UTF-8. (Trying to insert the body_html in to our database) - Is this something that the package can help with in terms of enforcing the UTF-8? If not no worries I'll continue looking in to it
