### ISSUE TITLE
use since take a long time

### ISSUE THREAD

**Issue by Romoloso** [Webklex/laravel-imap#257]
I used `since` like doc said:
```
$count = $folder->query()->since('10.10.2019')->count();
```
but it always times out, when I use all() instead since, it worked perfectly . 
Did I write something wrong ?

**Comment by kapitannwel** [comment]
i think it is a question of how many emails does it's reading. i have about 30 emails only that I am reading for a specific folder (which i separated from inbox using a filter rule) and it is taking me about 6 minutes. have you tried querying one day only so that you can estimately average how long it would take?

**Comment by Romoloso** [comment]
@kapitan

> i think this is also a question of how many emails does it's reading. i have about 50 emails only that I am reading for a specific folder (which i separated from inbox using a filter rule) and it is taking me about 6 minutes. is it querying one day only so that you can estimately average how long it would take?
> 
> also, have you check the maximum execution time of your server _(ex. php.ini)_?

my php.ini max_execution_time=30, but the request has exceeded 30 seconds, sometimes latan

> i think this is also a question of how many emails does it's reading. i have about 50 emails only that I am reading for a specific folder (which i separated from inbox using a filter rule) and it is taking me about 6 minutes. is it querying one day only so that you can estimately average how long it would take?
> 
> also, have you check the maximum execution time of your server _(ex. php.ini)_?

my php.ini max_execution_time=30, but the request has exceeded 30 seconds, sometimes lasts for minutes.

can you share your filter rules to me, please? it had took me a few days for this!

**Comment by kapitannwel** [comment]
we are currently using a gmail suite, we have email addresses like abcde@companyname.com but we are opening it on gmail. that is why i can make a filter rule online. but i guess it is not applicable to you since you want all email on your inbox.

i guess you need to adjust your maximum execution time?

p.s. - i am currently using `->since()` with no problem at all.

**Comment by Romoloso** [comment]
@kapitannwel @Webklex  
hah,thank you very much.  I have figure out by using `whereSince()`.
But I got another error in `webklex\laravel-imap\src\IMAP\Message.php` 609 line,  it said that `$personalParts`  is invalid argument supplied for foreach().  

I print out all `$personalParts`, it sometimes can be null, but only a few.  
 I solved it by try...catch...  and add keyword `continue` in catch so that is can keep running.

I don't know if it is a bug, maybe you can help~~~
