### ISSUE TITLE
Get message by ID | Reliable way to get specific message

### ISSUE THREAD

**Issue by SDCRoman** [Webklex/laravel-imap#269]
I want to retrieve the contents of a specific message.

In the docs I found two types of IDs:

```
getMessageId()
getUid()
```
Question 1:

Its also written that uid can change and is not unique. I wonder whats the purpose of the uid? How often can it change. I need the ID for immediate access.

Question 2:

I dont understand how I would use the message ID to retrieve a message, I does not work here as this function expects a uid:

`$oMessage = $oFolder->getMessage($uid = 1);`

---

I found a similar question already, where you propose to build a custom ID:
https://github.com/Webklex/laravel-imap/issues/136

`$token = $message->getUid().'/'.$folder->name.'/'.$message->getDate()->timestamp;`

But here you use the uid, if it is not unique, then the custom token is not unique aswell. 

---

Any other ideas how I can get a specific message with a unique identifier?

**Comment by Webklex** [comment]
Hi @SDCRoman ,
you are correct. The UID is not unique and can change. It's basically just an folder depending item index. Imagine you have a folder containing a lot of files and you sort them by date. The numeric file index (first, second, third, etc..) would represent the UID.

An example*:
- Your INBOX.test folder contains 10 messages (UID 1-10) and INBOX.trash is empty
- You move message (UID 10) from INBOX.test to INBOX.trash
  - message UID 10 becomes UID 1 in INBOX.trash
- Your INBOX.test folder now contains 9 messages (UID 1-9) and INBOX.trash one message (UID 1)
- You receive a new message in INBOX.test which will get the next available UID. In this case 10 since 9 is the highest UID in INBOX.test

If you would fetch the message (UID 10) from INBOX.test you would receive the wrong message. If you fetch UID 10 from INBOX.trash the result would be `null`.

If you use something like the token to identify a message, you have several data points to verify you're fetching the correct message. For example checking if the message date matches :)

*I made those UIDs up. Your Mail server/provider might handle it differently.

**Comment by SDCRoman** [comment]
Thanks again for the fast and detailed reply. 

This helps a lot.
