### ISSUE TITLE
Possible bug in certificate validation?

### ISSUE THREAD

**Issue by mynamespace** [Webklex/laravel-imap#355]
Hi and thank you for this component.
I think there is an inverted condition inside the file `Connection\Protocols\Protocol.php`, function `defaultSocketOptions()`.

	private function defaultSocketOptions() {
		return $this->getCertValidation()
			? [
				'ssl' => [
					'verify_peer_name' => false,
					'verify_peer'      => false,
				]
			]
			: [];
	}

if `$this->getCertValidation()` returns `true`, `defaultSocketOptions()` returns options to NOT validate the certificate. I had to put 'cert_validation' to true in my config to disable the validation. So I think it should be this way:

	private function defaultSocketOptions() {
		return $this->getCertValidation()
			? [] : [
				'ssl' => [
					'verify_peer_name' => false,
					'verify_peer'      => false,
				]
			];
	}

Hope it helps :)
Edit: this is inside `php-imap` package, maybe I should have opened this issue there

**Comment by Webklex** [comment]
Hi @mynamespace ,
thanks for your report. It seems indeed strange.. but I think I know the reason - there is a step missing:
```php
$stream = stream_socket_client($socket, $errno, $errstr, $timeout,
            STREAM_CLIENT_CONNECT,
            stream_context_create($this->defaultSocketOptions())
);
```
This is the only part where the method is called and where the socket options should be updated with the actual account setting based on the currently not provided information if the certs should be validated or not. 

`Protocol::defaultSocketOptions()` should not care if the certs get validated but actually care about the used transport method.

I'm closing this issue here. Please feel free to reopen it under [webklex/php-imap](https://github.com/Webklex/php-imap/issues/new?template=bug_report.md). However I have it on my todo-list - will be fixed within the next few days :)

Thanks again for your report.

Best regards,
