### ISSUE TITLE
Fetch E-Mails using Date Time

### ISSUE THREAD

**Issue by 91Abdullah** [Webklex/laravel-imap#357]
Hi, thanks for the wonderful library I've been using it since 2018 and I found it amazing for IMAP / POP3 both protocols. However, there's an issue on POP3 server you can't fetch new messages like you do in IMAP alternatively I've to move to some other criteria like `since` or through UID but UID also gets reset. Only criteria to fetch remains is through since but I've checked and found that since only supports date not like like I can do this:

`$inbox->query()->since('19.10.2020')->setFetchBody(false)->setFetchAttachment(false)->count()`

But can't do this:

`$inbox->query()->since('19.10.2020 02:01:00')->setFetchBody(false)->setFetchAttachment(false)->count()`

I wanted to ask if there is any way to fetch emails using date & time both?

**Comment by Webklex** [comment]
Hi @91Abdullah ,
unfortunately this completely depends on your mail server / provider. If they support a datetime format, you could set it in your imap.php config file under `date_format`. Perhaps `d-M-Y H:i:s` works, but to be honest I doubt that.. 

Keep in mind that the `date` header is set by the client who ever sent you the mail. For example: I can send you an email which has a date in the future or past. This sometimes happens if you work with people in different timezone and or misconfigured mail clients. Relying on the date and time to check for new mails isn't reliable either. The best would be to use `idle`. If you can't use imap, you could only fetch `unseen` messages, or move all messages after the import into an other folder. However this would require a single user - so this doesn't work if more then one program / client access the same account.

Best regards,

**Comment by 91Abdullah** [comment]
@Webklex Thanks for replying in such a short time. 

Previously, I was fetching through unseen messages and it did come out as a feasible solution because server there were approx more than 8000 unseen messages. Anyways, I switched to UID method in which I take last item from my database let's say it was 8000 and I keep on fetching messages until I reach end of `countMessages()`  but I don't know each UID gets reset previously it was 8815 now it is 8605.

Is there anyway I can check if my server supports `date_format` as `d-M-Y H:i:s`?

**Comment by 91Abdullah** [comment]
@Webklex is it possible I can set read flag on email and then fetch emails that are unread? Like the way outlook does!

**Comment by Webklex** [comment]
Hi @91Abdullah ,
it's actually pretty simple to test if datetime is support - just try it ;) If it works, it's supported - if not, it's not. Perhaps ask your mail provider if they support it and if so in which format.

If you don't want to fetch 8000+ messages at once, you could limit your result and process chunks of idk 50 messages:
```php
$messages = $folder->query()->all()->limit(50)->get();
```
https://github.com/Webklex/php-imap#result-limiting

You can also flag the fetches messages as "seen" by adding `markAsRead()` to your query, or by adding a flag manually.
https://github.com/Webklex/php-imap#message-flags

Best regards,
