### ISSUE TITLE
Invalid message date. ID:" GetMessagedFailedException

### ISSUE THREAD

**Issue by dannylifino** [Webklex/laravel-imap#412]
**Describe the bug**
I am trying to fetch all messages from the mailboxes, which was working fine for a while. However it seems that a message with an invalid message date throws the GetMessagesFailedException, whereas I cannot get this to work without the use of a dirty workaround. Furthermore, there are no weird emails retrieved in the mailbox either.

**To Reproduce**

To note is that this used to work for weeks until a message appeared with an 'Invalid message date'. 
Simple code: $this->inboxFolder->messages()->all()->get();

**Expected behavior**
I expect it to return all messages as usual

**Screenshots**
[https://ibb.co/K61MGN1](url)

**Desktop / Server (please complete the following information):**
 - OS: Windows 10
- PHP: 7.4.10
 - Version: 2.4.9

**Comment by Webklex** [comment]
Hi @dannylifino ,
many thanks for your report.

I believe it is related to https://github.com/Webklex/laravel-imap/issues/45 and since v2 handled by [webklex/php-imap](https://github.com/Webklex/php-imap).
In general this is an expected behavior. If you don't like the way an invalid date gets handled, please feel welcome to create a new issue or feature request over at [webklex/php-imap](https://github.com/Webklex/php-imap).

Best regards,

**Comment by dannylifino** [comment]
Thanks for your response. So this would mean that I can't read a mailbox of 1000+ mails, because of 1 mail that has an invalid date.
Are there any alternatives to get all the mails without the invalid one?

**Comment by Shakil148** [comment]
@dannylifino, you can use $this->inboxFolder->messages()->all()->softFail()->get(); will ignore the invalid date one.
