### ISSUE TITLE
Deleting multiple messages in the Trash folder does not work correctly

### ISSUE THREAD

**Issue by AnastasiaDolgopolova** [Webklex/laravel-imap#422]
When I pass the uid array and run it through foreach to move to another folder it works fine.![Снимок1](https://user-images.githubusercontent.com/47051058/142991909-c35e0594-13ca-4123-9654-a40de62cd1ba.PNG)
But when I pass the uid array and pass it through foreach to delete messages, then all messages in the Trash folder are deleted, not just those that were passed in the array!?
![Снимок](https://user-images.githubusercontent.com/47051058/142991975-aff76576-b96f-4adc-b517-92ad921c2048.PNG)
(At the same time, deleting an array of messages in the Spam, Drafts folders destroyed () method works
/ or if you transfer only one message to the Trash folder, then the destroyed () method works well)

How can i work with delete () of multiple messages in Trash folder?

I get:
500 (Internal Server Error)
![Снимок](https://user-images.githubusercontent.com/47051058/142998048-2c0f8a58-af9d-414d-a582-f77ddaa4b3b4.PNG)

**Comment by Webklex** [comment]
Hi @AnastasiaDolgopolova ,
many thanks for your report. Unfortunately this isn't the right repository. Please head over to https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md and create it over there.

Please try to answer as many of the questions mentioned in the issue template as possible. Especially regarding the used software versions.

Perhaps this issue is related to https://github.com/Webklex/php-imap/issues/106?

Best regards,

**Comment by AnastasiaDolgopolova** [comment]
The issue has been moved to https://github.com/Webklex/php-imap/issues/182
