### ISSUE TITLE
hi, Long time link, unable to receive new mail information

### ISSUE THREAD

**Issue by JueMeiAlg** [Webklex/laravel-imap#424]
https://www.php-imap.com/frameworks/laravel/service

I set the process according to the prompt in this link. It is normal to receive and monitor mail for a period of time when it is just running. When I monitor for a long time, such as obtaining other time periods after 5 hours, I will find that new mail has not been monitored. Why

**Comment by Webklex** [comment]
Hi @JueMeiAlg ,
I don't know why. This could be caused by a whole lot of things. 
Lets start with the version: which version are you using? Have you tried v3.0.0-alpha?
Which software versions / os are you using?
How can I replicate this? What are the exact steps required to reproduce this?
Do you get any errors?
Are there any logs available / e.g. syslog?
Which email provider are you using (if you would like to share)?

Best regards,

**Comment by JueMeiAlg** [comment]
I use the laravel framework 7.0, laravel IMAP
The expansion pack version is 2.4
I use CentOS 7.0
The mail service provider used is gmail
PHP version: 7.3.24
There are no other error logs
How to reproduce?: After configuring services, it is normal to start listening for new mail. When no new mail enters the mailbox for a long time, IMAP will not receive the new message after a period of time or several hours

**Comment by Blear** [comment]
I also encountered this problem. Is there any solution?

**Comment by Webklex** [comment]
Hi @JueMeiAlg @Blear ,
I believe to have determined and fixed the issue with the latest release. Please update your `webklex/php-imap` dependency to >= [v4.0.0](https://github.com/Webklex/php-imap/releases/tag/4.0.0) and try again.

Best regards & happy coding,
