### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by RhRU** [Webklex/laravel-imap#50]
Is there a way to paginate the messages of the mailboxes?
For example Getting a larger inbox like outlook or gmail?

**Comment by Webklex** [comment]
Hi @RhRU ,
so you want to reveice only lets say 15 messages at once and with the next request perhaps the next 15? This might be possible if you play with the native imap_search function and find the correct criteria. However if you do so please let me know. I would like to support this feature within a future release.

If you don't care about the amount of messages you receive with each call you can archive it currently with something like:
``` php
use Webklex\IMAP\Facades\Client;

/** @var \Webklex\IMAP\Client $oClient */
$oClient = Client::account('default');
$oClient->connect();

/** @var \Webklex\IMAP\Folder $oFolder */
$oFolder = $oClient->getFolder('INBOX.name');

$aCollection = collect($oFolder->getMessages());
$aPage = $aCollection->forPage(2, 15);

 /** @var \Webklex\IMAP\Message $oMessage */
foreach($aPage as $oMessage){
    echo $oMessage->subject.'<br />';
}
```

If you want to use a more solid way take a look at the [LengthAwarePaginator](https://laravel.com/docs/5.5/pagination#displaying-pagination-results) provided by Laravel:
``` php
$aCollection = collect($oFolder->getMessages());
$page = Input::get('page', 1);
$per_page = 15;

$paginator = new LengthAwarePaginator(
    $aCollection->forPage($page, $per_page), $aCollection->count(), $per_page, $page
);
```

Please note that you have to update to the latest version in order to use the getFolder function.
