### ISSUE TITLE
Confusing default configuration values

### ISSUE THREAD

**Issue by emilv** [Webklex/laravel-imap#66]
The library assumes that there will exist a default account, and that account must have all properties configured.

In particular I tried to use this configuration:

```

    'accounts' => [
        'default' => [
            'port' => 993,
            'encryption' => 'tls',
            'validate_cert' => true,
        ],
        'grappling' => [
            'host' => 'mail.example.com',
            'username' => 'blaha@example.com',
            'password' => env('IMAP_GRAPPLING_PASSWORD', null),
        ],
    ],
```

But in [Client::setConfig](https://github.com/Webklex/laravel-imap/blob/3c3fd5fe0c07ececd5c1837c09503e1888d59e27/src/IMAP/Client.php#L123) only configuration properties from the default account will ever be set.

Expected behavior is that all the values from both `grappling` are used, with default values from `default`.

**Comment by Webklex** [comment]
Hi @emilv ,
please make sure you published the package config file so it is available in your laravel config folder (config/imap.php) and take a look at the original config file: [src/config/imap.php](https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php)

You can define several accounts inside the `accounts` array. The `default` account which is currently placed inside, describes the account which will be used if none is specified.

If you are only using one account you don't have to add any account information inside the `imap.php` config file, because you can use the env-variables to archive the same.

You usually don't have to use Client::setConfig() at all - only if you want to manipulate configs during the runtime..

Hope I could help :)

**Comment by emilv** [comment]
I don't care about the default account. The confusion here is that the *only* config keys you are allowed to set are those that are defined on the default account. Look again on my example. I removed host, username and password from the default account. That makes it impossible to set those same values on the grappling account.

**Comment by Webklex** [comment]
Ah I see. Yes you're right. I will move to a fixed config set - something like this:
```php
public function setConfig(array $config) {
        $defaultAccount = config('imap.default');
        $defaultConfig  = config("imap.accounts.$defaultAccount");

        $availableConfig = ['host', 'port', 'encryption', 'validate_cert', 'username', 'password'];

        foreach($availableConfig as $key){
            $this->$key = isset($config[$key]) ? $config[$key] : $defaultConfig[$key];
        }

        return $this;
}
```

**Comment by Webklex** [comment]
Hi @emilv ,
I just released a new version which handles the "config setting process" a bit different. Its now based on fixed keys :)

Ref.: [v. 1.0.5.5](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.5)
